name: Nightly Android

on:
  # Automatically run at the end of every day.
  schedule:
    - cron: '0 0 * * *'
  push:

env:
  # runner.workspace = /home/runner/work/ladybird
  # github.workspace = /home/runner/work/ladybird/ladybird
  LADYBIRD_SOURCE_DIR: ${{ github.workspace }}
  CCACHE_DIR: ${{ github.workspace }}/.ccache
  VCPKG_ROOT:  ${{ github.workspace }}/Toolchain/Tarballs/vcpkg
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

jobs:
  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os_name: ['Android']
        os: [macos-13]

    steps:
      - name: Install Python
        run: brew install python@3.13